"""Parse CreatorPulse Kafka-style events and prepare MySQL aggregate rows.

This is the offline, testable precursor to Spark Streaming. It reads NDJSON
events generated by kafka_tools/mock_producer.py and computes rows compatible
with the Spark JDBC smoke tables.
"""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_EVENTS_PATH = ROOT_DIR / "kafka_tools" / "out" / "mock_events.ndjson"


def pct(numerator: float, denominator: float) -> float:
    if denominator <= 0:
        return 0.0
    return round(numerator / denominator, 6)


def load_events(path: Path = DEFAULT_EVENTS_PATH) -> list[dict[str, Any]]:
    events = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            events.append(json.loads(line))
    return events


def video_stats_events(events: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [event for event in events if event.get("event_type") == "video_stats"]


def aggregate_platform_metrics(
    events: list[dict[str, Any]],
    run_id: str,
    calculated_at: str,
) -> list[dict[str, Any]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for event in video_stats_events(events):
        grouped.setdefault(event["platform"], []).append(event)

    rows = []
    for platform, platform_events in sorted(grouped.items()):
        total_views = sum(event["stats"]["play_count"] for event in platform_events)
        new_followers = sum(event["growth"]["new_followers"] for event in platform_events)
        rows.append(
            {
                "run_id": run_id,
                "creator_id": platform_events[0]["creator_id"],
                "platform": platform,
                "total_views": total_views,
                "new_followers": new_followers,
                "video_count": len(platform_events),
                "conversion_rate": pct(new_followers, total_views),
                "calculated_at": calculated_at,
            }
        )
    return rows


def aggregate_video_contributions(
    events: list[dict[str, Any]],
    run_id: str,
    calculated_at: str,
    limit: int = 10,
) -> list[dict[str, Any]]:
    ranked = sorted(video_stats_events(events), key=lambda event: event["growth"]["new_followers"], reverse=True)[:limit]
    rows = []
    for position, event in enumerate(ranked, start=1):
        views = event["stats"]["play_count"]
        followers = event["growth"]["new_followers"]
        rows.append(
            {
                "run_id": run_id,
                "rank_position": position,
                "creator_id": event["creator_id"],
                "video_id": event["content_id"],
                "platform": event["platform"],
                "title": event.get("title") or event["content_id"],
                "views": views,
                "new_followers": followers,
                "conversion_rate": pct(followers, views),
                "calculated_at": calculated_at,
            }
        )
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description="Aggregate CreatorPulse Kafka-style NDJSON events")
    parser.add_argument("--events", type=Path, default=DEFAULT_EVENTS_PATH)
    parser.add_argument("--run-id", default="kafka_events_dry_run_001")
    args = parser.parse_args()

    events = load_events(args.events)
    calculated_at = datetime.now(UTC).replace(microsecond=0, tzinfo=None).isoformat()
    platform_rows = aggregate_platform_metrics(events, args.run_id, calculated_at)
    contribution_rows = aggregate_video_contributions(events, args.run_id, calculated_at)
    print(
        json.dumps(
            {
                "status": "ok",
                "mode": "dry-run",
                "inputEvents": len(events),
                "counts": {
                    "video_stats_events": len(video_stats_events(events)),
                    "spark_platform_metric_summaries": len(platform_rows),
                    "spark_video_follower_contributions": len(contribution_rows),
                },
                "sample": {
                    "platform": platform_rows[0] if platform_rows else None,
                    "videoContribution": contribution_rows[0] if contribution_rows else None,
                },
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
