"""Parse CreatorPulse Kafka-style events and prepare MySQL aggregate rows.

This is the offline, testable precursor to Spark Streaming. It reads NDJSON
events generated by kafka_tools/mock_producer.py and computes rows compatible
with the Spark JDBC smoke tables.
"""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_EVENTS_PATH = ROOT_DIR / "kafka_tools" / "out" / "mock_events.ndjson"


def pct(numerator: float, denominator: float) -> float:
    if denominator <= 0:
        return 0.0
    return round(numerator / denominator, 6)


def bounded_score(value: float) -> float:
    return round(max(0.0, min(100.0, value)), 2)


def event_timestamp(event: dict[str, Any]) -> str:
    return str(event.get("fetch_time") or "")


def snapshot_id(*parts: Any) -> str:
    raw = "_".join(str(part) for part in parts if part is not None)
    safe = "".join(char if char.isalnum() else "_" for char in raw)
    return safe[:96]


def normalize_source(source: str) -> str:
    mapping = {
        "recommendation": "recommend",
        "recommend": "recommend",
        "following": "follow",
        "follow": "follow",
    }
    normalized = source.strip().lower()
    return mapping.get(normalized, normalized)


def metric_delta(growth: dict[str, Any], stats: dict[str, Any], delta_key: str, total_key: str) -> int:
    explicit = growth.get(delta_key)
    if explicit is not None:
        return int(explicit)
    return max(0, int(int(stats.get(total_key, 0)) * 0.0012))


def load_events(path: Path = DEFAULT_EVENTS_PATH) -> list[dict[str, Any]]:
    events = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            events.append(json.loads(line))
    return events


def video_stats_events(events: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [event for event in events if event.get("event_type") == "video_stats"]


def latest_video_stats_events(events: list[dict[str, Any]]) -> list[dict[str, Any]]:
    latest: dict[tuple[str, str], dict[str, Any]] = {}
    for event in video_stats_events(events):
        key = (event["creator_id"], event["content_id"])
        current = latest.get(key)
        if current is None or event_timestamp(event) >= event_timestamp(current):
            latest[key] = event
    return list(latest.values())


def archive_raw_video_stat_events(events: list[dict[str, Any]]) -> list[dict[str, Any]]:
    rows = []
    for event in video_stats_events(events):
        stats = event["stats"]
        growth = event["growth"]
        fetch_time = event_timestamp(event)
        rows.append(
            {
                "event_id": event["event_id"],
                "creator_id": event["creator_id"],
                "platform": event["platform"],
                "video_id": event["content_id"],
                "event_type": event["event_type"],
                "event_date": fetch_time[:10],
                "fetch_time": fetch_time,
                "play_delta": growth.get("play_growth_5s") or stats["play_count"],
                "like_delta": metric_delta(growth, stats, "like_delta", "like_count"),
                "comment_delta": metric_delta(growth, stats, "comment_delta", "comment_count"),
                "share_delta": metric_delta(growth, stats, "share_delta", "share_count"),
                "save_delta": metric_delta(growth, stats, "save_delta", "save_count"),
                "profile_visit_delta": growth["profile_visits"],
                "new_follower_delta": growth.get("new_followers_delta", growth["new_followers"]),
                "lost_follower_delta": growth.get("lost_followers", 0),
                "raw_payload_json": json.dumps(event, ensure_ascii=False, sort_keys=True),
            }
        )
    return rows


def aggregate_platform_metrics(
    events: list[dict[str, Any]],
    run_id: str,
    calculated_at: str,
) -> list[dict[str, Any]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for event in video_stats_events(events):
        grouped.setdefault(event["platform"], []).append(event)

    rows = []
    for platform, platform_events in sorted(grouped.items()):
        total_views = sum(event["stats"]["play_count"] for event in platform_events)
        new_followers = sum(event["growth"]["new_followers"] for event in platform_events)
        rows.append(
            {
                "run_id": run_id,
                "creator_id": platform_events[0]["creator_id"],
                "platform": platform,
                "total_views": total_views,
                "new_followers": new_followers,
                "video_count": len(platform_events),
                "conversion_rate": pct(new_followers, total_views),
                "calculated_at": calculated_at,
            }
        )
    return rows


def aggregate_video_metric_snapshots(events: list[dict[str, Any]], collected_at: str) -> list[dict[str, Any]]:
    rows = []
    for event in sorted(latest_video_stats_events(events), key=lambda item: (item["creator_id"], item["content_id"])):
        stats = event["stats"]
        growth = event["growth"]
        views = stats["play_count"]
        likes = stats["like_count"]
        comments = stats["comment_count"]
        shares = stats["share_count"]
        saves = stats["save_count"]
        profile_visits = growth["profile_visits"]
        new_followers = growth["new_followers"]
        rows.append(
            {
                "snapshot_id": snapshot_id("vms", event["creator_id"], event["content_id"], collected_at),
                "video_id": event["content_id"],
                "creator_id": event["creator_id"],
                "platform": event["platform"],
                "views": views,
                "likes": likes,
                "comments": comments,
                "shares": shares,
                "saves": saves,
                "profile_visits": profile_visits,
                "new_followers": new_followers,
                "completion_rate": stats.get("completion_rate", 0.0),
                "average_watch_seconds": stats.get("average_watch_seconds", 0),
                "engagement_rate": pct(likes + comments + shares + saves, views),
                "conversion_rate": pct(new_followers, views),
                "comment_rate": pct(comments, views),
                "save_rate": pct(saves, views),
                "share_rate": pct(shares, views),
                "collected_at": collected_at,
            }
        )
    return rows


def aggregate_video_traffic_source_metrics(events: list[dict[str, Any]]) -> list[dict[str, Any]]:
    rows = []
    for event in sorted(latest_video_stats_events(events), key=lambda item: (item["creator_id"], item["content_id"])):
        for source, source_metrics in sorted((event.get("traffic_source") or {}).items()):
            normalized_source = normalize_source(source)
            views = source_metrics.get("views", 0)
            new_followers = source_metrics.get("new_followers", 0)
            rows.append(
                {
                    "video_id": event["content_id"],
                    "source": normalized_source,
                    "views": views,
                    "new_followers": new_followers,
                    "conversion_rate": source_metrics.get("conversion_rate", pct(new_followers, views)),
                    "save_rate": source_metrics.get("save_rate", pct(event["stats"].get("save_count", 0), event["stats"].get("play_count", 0))),
                    "comment_rate": source_metrics.get("comment_rate", pct(event["stats"].get("comment_count", 0), event["stats"].get("play_count", 0))),
                }
            )
    return rows


def aggregate_creator_metric_snapshots(events: list[dict[str, Any]], metric_date: str) -> list[dict[str, Any]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for event in latest_video_stats_events(events):
        grouped.setdefault(event["creator_id"], []).append(event)

    rows = []
    for creator_id, creator_events in sorted(grouped.items()):
        total_views = sum(event["stats"]["play_count"] for event in creator_events)
        total_interactions = sum(
            event["stats"]["like_count"] + event["stats"]["comment_count"] + event["stats"]["share_count"] + event["stats"]["save_count"]
            for event in creator_events
        )
        profile_visits = sum(event["growth"]["profile_visits"] for event in creator_events)
        new_followers = sum(event["growth"]["new_followers"] for event in creator_events)
        play_delta = sum(event["growth"].get("play_growth_5s") or event["stats"]["play_count"] for event in creator_events)
        lost_followers = 0
        net_followers = new_followers - lost_followers
        view_to_follower_rate = pct(new_followers, play_delta)
        engagement_rate = pct(total_interactions, total_views)
        profile_conversion_rate = pct(new_followers, profile_visits)
        stickiness_score = bounded_score(engagement_rate * 180)
        growth_health_score = bounded_score(view_to_follower_rate * 900 + profile_conversion_rate * 100 + stickiness_score * 0.25)
        rows.append(
            {
                "snapshot_id": snapshot_id("cms", creator_id, metric_date),
                "creator_id": creator_id,
                "metric_date": metric_date,
                "total_followers": new_followers,
                "new_followers": new_followers,
                "lost_followers": lost_followers,
                "net_followers": net_followers,
                "total_views": total_views,
                "total_interactions": total_interactions,
                "profile_visits": profile_visits,
                "follower_growth_rate": 0.0,
                "view_to_follower_rate": view_to_follower_rate,
                "stickiness_score": stickiness_score,
                "growth_health_score": growth_health_score,
            }
        )
    return rows


def aggregate_video_contributions(
    events: list[dict[str, Any]],
    run_id: str,
    calculated_at: str,
    limit: int = 10,
) -> list[dict[str, Any]]:
    ranked = sorted(video_stats_events(events), key=lambda event: event["growth"]["new_followers"], reverse=True)[:limit]
    rows = []
    for position, event in enumerate(ranked, start=1):
        views = event["stats"]["play_count"]
        followers = event["growth"]["new_followers"]
        rows.append(
            {
                "run_id": run_id,
                "rank_position": position,
                "creator_id": event["creator_id"],
                "video_id": event["content_id"],
                "platform": event["platform"],
                "title": event.get("title") or event["content_id"],
                "views": views,
                "new_followers": followers,
                "conversion_rate": pct(followers, views),
                "calculated_at": calculated_at,
            }
        )
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description="Aggregate CreatorPulse Kafka-style NDJSON events")
    parser.add_argument("--events", type=Path, default=DEFAULT_EVENTS_PATH)
    parser.add_argument("--run-id", default="kafka_events_dry_run_001")
    args = parser.parse_args()

    events = load_events(args.events)
    calculated_at = datetime.now(UTC).replace(microsecond=0, tzinfo=None).isoformat()
    metric_date = calculated_at[:10]
    raw_event_rows = archive_raw_video_stat_events(events)
    platform_rows = aggregate_platform_metrics(events, args.run_id, calculated_at)
    contribution_rows = aggregate_video_contributions(events, args.run_id, calculated_at)
    video_snapshot_rows = aggregate_video_metric_snapshots(events, calculated_at)
    traffic_rows = aggregate_video_traffic_source_metrics(events)
    creator_snapshot_rows = aggregate_creator_metric_snapshots(events, metric_date)
    print(
        json.dumps(
            {
                "status": "ok",
                "mode": "dry-run",
                "inputEvents": len(events),
                "counts": {
                    "video_stats_events": len(video_stats_events(events)),
                    "raw_video_stat_events": len(raw_event_rows),
                    "spark_platform_metric_summaries": len(platform_rows),
                    "spark_video_follower_contributions": len(contribution_rows),
                    "video_metric_snapshots": len(video_snapshot_rows),
                    "video_traffic_source_metrics": len(traffic_rows),
                    "creator_metric_snapshots": len(creator_snapshot_rows),
                },
                "sample": {
                    "rawVideoStatEvent": raw_event_rows[0] if raw_event_rows else None,
                    "platform": platform_rows[0] if platform_rows else None,
                    "videoContribution": contribution_rows[0] if contribution_rows else None,
                    "videoMetricSnapshot": video_snapshot_rows[0] if video_snapshot_rows else None,
                    "creatorMetricSnapshot": creator_snapshot_rows[0] if creator_snapshot_rows else None,
                },
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
